name: fWeather
description: Fast way to knowing temperature of a city.

publish_to: 'none'

version: 1.0.1+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  http: ^0.12.2
  flutter_spinkit: ^4.1.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^0.1.2
  
flutter:
  uses-material-design: true

  assets:
    - images/