name: fWeather
description: A Weather App using Flutter and its Packages

version: 1.2.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  geolocator: ^6.0.0+4
  http: ^0.12.2
  flutter_spinkit: ^4.1.2+1
  font_awesome_flutter: ^8.8.1
  weather_icons: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/pic.png
